[tool.poetry]
name = "heliotrope"
version = "7.0.0"
description = "Hitomi.la mirror api"
authors = ["Ryu Juheon <saidbysolo@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sanic = "^24.6.0"
aiohttp = "^3.10.10"
sqlalchemy = "^2.0.36"
black = "^24.10.0"
isort = "^5.13.2"

[tool.pyright]
include = ["heliotrope"]
typeCheckingMode = "strict"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
