"""ondelete cascade

Revision ID: 45c39123b775
Revises:
Create Date: 2025-05-22 10:26:15.176866

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45c39123b775"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "galleryinfo_artist_galleryinfo_id_fkey",
        "galleryinfo_artist",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "galleryinfo_artist",
        "galleryinfo",
        ["galleryinfo_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "galleryinfo_character_galleryinfo_id_fkey",
        "galleryinfo_character",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "galleryinfo_character",
        "galleryinfo",
        ["galleryinfo_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "galleryinfo_group_galleryinfo_id_fkey", "galleryinfo_group", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "galleryinfo_group",
        "galleryinfo",
        ["galleryinfo_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "galleryinfo_language_galleryinfo_id_fkey",
        "galleryinfo_language",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "galleryinfo_language",
        "galleryinfo",
        ["galleryinfo_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "galleryinfo_parody_galleryinfo_id_fkey",
        "galleryinfo_parody",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "galleryinfo_parody",
        "galleryinfo",
        ["galleryinfo_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "galleryinfo_tag_galleryinfo_id_fkey", "galleryinfo_tag", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "galleryinfo_tag",
        "galleryinfo",
        ["galleryinfo_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "galleryinfo_tag", type_="foreignkey")
    op.create_foreign_key(
        "galleryinfo_tag_galleryinfo_id_fkey",
        "galleryinfo_tag",
        "galleryinfo",
        ["galleryinfo_id"],
        ["id"],
    )
    op.drop_constraint(None, "galleryinfo_parody", type_="foreignkey")
    op.create_foreign_key(
        "galleryinfo_parody_galleryinfo_id_fkey",
        "galleryinfo_parody",
        "galleryinfo",
        ["galleryinfo_id"],
        ["id"],
    )
    op.drop_constraint(None, "galleryinfo_language", type_="foreignkey")
    op.create_foreign_key(
        "galleryinfo_language_galleryinfo_id_fkey",
        "galleryinfo_language",
        "galleryinfo",
        ["galleryinfo_id"],
        ["id"],
    )
    op.drop_constraint(None, "galleryinfo_group", type_="foreignkey")
    op.create_foreign_key(
        "galleryinfo_group_galleryinfo_id_fkey",
        "galleryinfo_group",
        "galleryinfo",
        ["galleryinfo_id"],
        ["id"],
    )
    op.drop_constraint(None, "galleryinfo_character", type_="foreignkey")
    op.create_foreign_key(
        "galleryinfo_character_galleryinfo_id_fkey",
        "galleryinfo_character",
        "galleryinfo",
        ["galleryinfo_id"],
        ["id"],
    )
    op.drop_constraint(None, "galleryinfo_artist", type_="foreignkey")
    op.create_foreign_key(
        "galleryinfo_artist_galleryinfo_id_fkey",
        "galleryinfo_artist",
        "galleryinfo",
        ["galleryinfo_id"],
        ["id"],
    )
    # ### end Alembic commands ###
