name: CI

on:
  push:
    branches: [ main, develop, release, hotfix ]
  pull_request:
    branches: [ main, develop, release, hotfix ]
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Setup poetry
        run: |
          python -m pip install pip
          pip install poetry
          #add path for poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install --no-interaction --with style
      - name: Check style with black
        run: poetry run black --check .
      - name: Check style with isort
        run: poetry run isort --check .
        
  type:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Setup poetry
        run: |
          python -m pip install pip
          pip install poetry
          #add path for poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install --no-interaction --with type
      - name: Check type
        run: poetry run pyright
      - name: Check untyped function
        run: poetry run mypy ./heliotrope
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_heliotrope
        ports:
          - 127.0.0.1:5432:5432
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Setup poetry
        run: |
          python -m pip install pip
          pip install poetry
          #add path for poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install --no-interaction --with test
      - name: Check test
        run: poetry run pytest --asyncio-mode=auto --cov=heliotrope --cov-report=xml
      - name: Codecov
        uses: codecov/codecov-action@v5

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [ type, test, style ]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name == 'release' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
